version: '3.4'
services:
  redis-master:
    image: redis:7.0
    container_name: redis-master
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - 16379:16379
    volumes:
      - /project/sms/docker/docker-volumes/redis/redis-cluster/master/data:/data
      - /project/sms/docker/docker-volumes/redis/redis-cluster/master/conf/:/etc/redis/

  redis-slave1:
    image: redis:7.0
    container_name: redis-slave1
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - 16380:16380
    volumes:
      - /project/sms/docker/docker-volumes/redis/redis-cluster/slave1/data:/data
      - /project/sms/docker/docker-volumes/redis/redis-cluster/slave1/conf/:/etc/redis/

  redis-slave2:
    image: redis:7.0
    container_name: redis-slave2
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - 16381:16381
    volumes:
      - /project/sms/docker/docker-volumes/redis/redis-cluster/slave2/data:/data
      - /project/sms/docker/docker-volumes/redis/redis-cluster/slave2/conf/:/etc/redis/
